# Define la imagen base
FROM node:14-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY package*.json ./
COPY app.js ./

# Instala las dependencias
RUN npm install

# Expone el puerto 3000
EXPOSE 3000

# Define el comando por defecto para ejecutar la aplicación
CMD ["npm", "start"]
